// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8mMOaUoCp6NPVkAGYxXEFKm8Ax13U9fs',
    appId: '1:325286518688:ios:54e0e5c7cda95b09e0cec5',
    messagingSenderId: '325286518688',
    projectId: 'jaclean-23b8d',
    storageBucket: 'jaclean-23b8d.firebasestorage.app',
    iosBundleId: 'com.example.qjaclean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8mMOaUoCp6NPVkAGYxXEFKm8Ax13U9fs',
    appId: '1:325286518688:ios:54e0e5c7cda95b09e0cec5',
    messagingSenderId: '325286518688',
    projectId: 'jaclean-23b8d',
    storageBucket: 'jaclean-23b8d.firebasestorage.app',
    iosBundleId: 'com.example.qjaclean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfBAjvhuy0RdM_OCS1-rW7fchlwZ4s79Y',
    appId: '1:325286518688:web:e9aabbab725942dee0cec5',
    messagingSenderId: '325286518688',
    projectId: 'jaclean-23b8d',
    authDomain: 'jaclean-23b8d.firebaseapp.com',
    storageBucket: 'jaclean-23b8d.firebasestorage.app',
    measurementId: 'G-GKGEYV57EC',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfBAjvhuy0RdM_OCS1-rW7fchlwZ4s79Y',
    appId: '1:325286518688:web:e9aabbab725942dee0cec5',
    messagingSenderId: '325286518688',
    projectId: 'jaclean-23b8d',
    authDomain: 'jaclean-23b8d.firebaseapp.com',
    storageBucket: 'jaclean-23b8d.firebasestorage.app',
    measurementId: 'G-GKGEYV57EC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDObqYyPrDCMs_zQFA-9mXNJ80qspOgpPU',
    appId: '1:325286518688:android:fbc8329186f1adf3e0cec5',
    messagingSenderId: '325286518688',
    projectId: 'jaclean-23b8d',
    storageBucket: 'jaclean-23b8d.firebasestorage.app',
  );

}